/* eslint-disable */
// This file is automatically generated, do not edit!

import '@atcute/client/lexicons';

declare module '@atcute/client/lexicons' {
	/** Describes the translation proxy instance */
	namespace XBasaDescribeServer {
		interface Params {}
		type Input = undefined;
		interface Output {
			engines: Engines;
		}
		interface Engine {
			[Brand.Type]?: 'x.basa.describeServer#engine';
			/** Supported language codes */
			languages: string[];
		}
		interface Engines {
			[Brand.Type]?: 'x.basa.describeServer#engines';
			deepl?: Engine;
			google?: Engine;
		}
	}

	/** Translates a given text into another language */
	namespace XBasaTranslate {
		interface Params {
			/** Text needing translation */
			text: string;
			/** Target language */
			to: string;
			/**
			 * Which translation service to use
			 * @default "google"
			 */
			engine?: 'google' | 'deepl';
			/**
			 * Source language
			 * @default "auto"
			 */
			from?: string;
		}
		type Input = undefined;
		interface Output {
			/** Translated text */
			result: string;
			/** Deteced language from source text */
			sourceLanguage?: string;
			/** Transliteration of source text */
			sourceTransliteration?: string;
			/** Transliteration of translated text */
			targetTransliteration?: string;
		}
	}

	interface Records {}

	interface Queries {
		'x.basa.describeServer': {
			output: XBasaDescribeServer.Output;
		};
		'x.basa.translate': {
			params: XBasaTranslate.Params;
			output: XBasaTranslate.Output;
		};
	}

	interface Procedures {}
}
